import os

class Config:
    RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
    RABBITMQ_PORT = int(os.getenv('RABBITMQ_PORT'))
    RABBITMQ_USER = os.getenv('RABBITMQ_USER')
    RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD')
    RABBITMQ_QUEUE_RECOGNITION_REQUEST = os.getenv('RABBITMQ_QUEUE_RECOGNITION_REQUEST')
    RABBITMQ_QUEUE_TUNE_REQUEST = os.getenv('RABBITMQ_QUEUE_TUNE_REQUEST')
    RABBITMQ_QUEUE_RECOGNITION_RESULTS = os.getenv('RABBITMQ_QUEUE_RECOGNITION_RESULTS')
    DB_CONNECTION_STRING = os.getenv('DB_CONNECTION_STRING')